# Generated by Django 3.0.6 on 2024-05-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('C_Ingresa', 'Conceptos Ingresa'), ('C_Inserta', 'Conceptos Inserta'), ('C_Modifica', 'Conceptos Modifica'), ('C_Elimina', 'Conceptos Elimina')],
            },
        ),
    ]
